const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function boot(seed){const elements=new Map(),storage=new Map([['rahlati-v1',JSON.stringify(seed?[seed]:[])],['rahlati-current',seed?.id||'']]);const element=key=>{if(!elements.has(key))elements.set(key,{innerHTML:'',textContent:'',classList:{add(){},remove(){},contains(){return true},toggle(){}},setAttribute(){},addEventListener(){},querySelector(){return null},querySelectorAll(){return[]},insertAdjacentHTML(pos,html){this.innerHTML+=html;},scrollIntoView(){},focus(){},style:{}});return elements.get(key);};const context=vm.createContext({console,URL,URLSearchParams,Intl,Date,Map,Set,Math,JSON,Number,String,Array,Object,RegExp,Promise,crypto:require('node:crypto').webcrypto,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},document:{documentElement:{},body:element('body'),querySelector:element,querySelectorAll:()=>[],addEventListener(){},getElementById:()=>null},navigator:{onLine:true},location:{protocol:'file:',search:'',pathname:'/'},history:{},setTimeout(){},clearTimeout(){},requestAnimationFrame(){},alert(){},window:{addEventListener(){}},IntersectionObserver:class{observe(){} disconnect(){}}});for(const file of ['planner-core.js','app.js','preview.js','upgrade.js','venue-guide.js','transit.js','trip-assistant.js'])vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});return{context,storage,elements};}
test('existing data survives startup even without old reset flag',()=>{let seed=JSON.parse(fs.readFileSync('istanbul-preview.json'));const b=boot(seed);assert.equal(JSON.parse(b.storage.get('rahlati-v1'))[0].places.length,128);});
test('all desktop/mobile shared sections render in Arabic and English',()=>{let seed=JSON.parse(fs.readFileSync('istanbul-preview.json'));const {context}=boot(seed);for(const locale of ['ar','en'])for(const section of ['overview','itinerary','places','bookings','mapView','budget','checklist','notes','lists']){const html=vm.runInContext(`lang='${locale}';tab='${section}';workspace(trip())`,context);assert(html.includes('workspace-content'),locale+section);assert(!html.includes('undefined'),locale+section);}});
test('imported copy retains main/extra split with a different ID',()=>{let seed=JSON.parse(fs.readFileSync('istanbul-preview.json'));seed.id='imported-copy';const {context}=boot(seed);const html=vm.runInContext("tab='itinerary';renderTab(trip())",context);assert(html.includes('preview-extras'));assert(html.includes('mainRoute'));});
test('empty home boots without a trip',()=>{const {elements}=boot();assert(elements.get('#app').innerHTML.includes('hero'));});

test('transit uses live origin links and each day closure calendar',()=>{const seed=JSON.parse(fs.readFileSync('istanbul-preview.json'));const {context}=boot(seed);const html=vm.runInContext("tab='itinerary';renderTab(trip())",context);assert(html.includes('transit-access'));assert(html.includes('opening-day'));assert(html.includes('travelmode=transit'));assert.equal(vm.runInContext("RahlatiTransit.closed({name:'Topkapi Palace Museum'},'2026-10-13')",context),true);assert.equal(vm.runInContext("RahlatiTransit.closed({name:'Topkapi Palace Museum'},'2026-10-11')",context),false);assert.equal(vm.runInContext("routeGroups(PlannerCore.main(trip(),'2026-10-11')).every(g=>g.length===2)",context),true);});
test('October seasonal closing and final entry catch actual plan conflicts',()=>{const {context}=boot(JSON.parse(fs.readFileSync('istanbul-preview.json')));for(const name of ['Maiden\'s Tower','The Blue Mosque'])assert.equal(vm.runInContext(`RahlatiVisit.problems(trip().places.find(p=>p.name===${JSON.stringify(name)}),trip().places.find(p=>p.name===${JSON.stringify(name)}).date).some(s=>s.includes('آخر دخول'))`,context),true);assert.equal(vm.runInContext("RahlatiTransit.hoursText(RahlatiTransit.rules['The Blue Mosque'],'2026-10-11')",context),'08:30–17:00');assert.equal(vm.runInContext("RahlatiTransit.hoursText(RahlatiTransit.rules['The Blue Mosque'],'2026-07-11')",context),'08:30–19:00');});
test('suggested days exclude weekly closures and distant return-day trips',()=>{const {context}=boot(JSON.parse(fs.readFileSync('istanbul-preview.json')));assert.equal(vm.runInContext("RahlatiVisit.suggestions(trip(),trip().places.find(p=>p.name==='Topkapi Palace Museum')).some(v=>v.date==='2026-10-13')",context),false);assert.equal(vm.runInContext("RahlatiVisit.suggestions(trip(),trip().places.find(p=>p.name==='Polonezköy')).some(v=>v.date===trip().end)",context),false);});
test('all 128 venues have visit guidance without turning unknown hours into open schedules',()=>{const {context}=boot(JSON.parse(fs.readFileSync('istanbul-preview.json')));assert.equal(vm.runInContext("trip().places.every(p=>VenueGuide.profiles[p.name]?.minutes>0)",context),true);assert.equal(vm.runInContext("RahlatiTransit.opening({name:'Beltur'})",context),undefined);const html=vm.runInContext("placeCard(trip().places.find(p=>p.name==='Lokma'),false)",context);assert(html.includes('غير موثّق'));assert(html.includes('ثبّت الفرع'));assert(html.includes('استبدله'));});
test('replacement keeps all venue data and makes a recoverable choice snapshot',()=>{const {context}=boot(JSON.parse(fs.readFileSync('istanbul-preview.json')));assert.equal(vm.runInContext("(()=>{const x=trip(),p=x.places.find(p=>p.listId==='extra'),q=x.places.find(p=>p.listId!=='extra'),old=q.order;RahlatiVisit.replace(x,p,q,q.date);return x.places.length===128&&p.listId===''&&q.listId==='extra'&&p.order===old&&p.time===''&&x.choiceUndo.length===128;})()",context),true);});
test('new Google Routes library handles browser keys, steps and Istanbul times',async()=>{const {context,storage}=boot(JSON.parse(fs.readFileSync('istanbul-preview.json')));storage.set('rahlati-google-key','TEST_KEY');vm.runInContext("globalThis.google={maps:{Map:function(){},importLibrary:async()=>({Route:{computeRoutes:async request=>{if(request.travelMode!=='TRANSIT'||request.intermediates||request.fields.includes('*'))throw Error('BAD_REQUEST');return{routes:[{durationMillis:600000,distanceMeters:2000,path:[],legs:[{steps:[{transitDetails:{transitLine:{shortName:'T1',vehicle:{name:'TRAM'}},departureStop:{name:'A'},arrivalStop:{name:'B'},departureTime:new Date('2026-10-10T07:00:00Z'),arrivalTime:new Date('2026-10-10T07:10:00Z')}}]}]}]};}}})}}",context);const html=await vm.runInContext("RahlatiTransit.route(trip().hotel,trip().places[0],new Date('2026-10-10T07:00:00Z')).then(RahlatiTransit.stepsHtml)",context);assert(html.includes('T1'));assert(html.includes('TRAM'));assert(html.includes('10'));assert(html.includes('A'));assert(html.includes('B'));});
