/* Public transport companion; existing trips remain untouched. */
(function(){
'use strict';
const L=(ar,en)=>lang==='ar'?ar:en, oldCard=placeCard, oldTab=renderTab, oldRender=render, oldSettings=settings;
let generation=0, loader=null, lastPosition=null, locationWatch=null;
const rules={
'Topkapi Palace Museum':{closed:[2],hours:'09:00–17:00',note:'ساعات شباك التذاكر',source:'https://millisaraylar.gov.tr/Lokasyon/2/Topkapi%20-Palace'},
'Dolmabahçe Palace':{closed:[1],hours:'09:00–17:00',note:'ساعات شباك التذاكر',source:'https://millisaraylar.gov.tr/Lokasyon/3/Dolmabahce-Sarayi'},
'Beylerbeyi Palace':{closed:[1],hours:'09:00–17:00',note:'ساعات شباك التذاكر',source:'https://www.millisaraylar.gov.tr/Lokasyon/4/Beylerbeyi-Sarayi?culture=en'},
'Istanbul Museum of Modern Art':{closed:[1],hours:'10:00–18:00',byDay:{5:'10:00–20:00'},note:'آخر دخول قبل الإغلاق بنصف ساعة',source:'https://www.istanbulmodern.org/en/visit/museum'},
'Pera Museum':{closed:[1],hours:'10:00–19:00',byDay:{0:'12:00–18:00',5:'10:00–22:00'},source:'https://www.peramuseum.org/home/visit'},
'The Museum of Innocence':{closed:[1],hours:'10:00–18:00',note:'التذاكر حتى 17:30',source:'https://www.masumiyetmuzesi.org/en/zi-yaret-g%C3%BCn-ve-saatleri'},
'Istanbul Toy Museum':{closed:[1],hours:'10:00–18:00',byDay:{0:'10:00–18:30',6:'10:00–18:30'},source:'https://istanbuloyuncakmuzesi.com/'},
'Rahmi M. Koç Museum':{closed:[1],hours:'09:30–17:30',byDay:{0:'09:30–18:00',6:'09:30–18:00'},source:'https://www.rmk-museum.org.tr/istanbul/en/visit-us/hours-and-prices'}
};
Object.assign(rules,{
'Sakıp Sabancı Museum':{closed:[1],hours:'10:00–18:00',note:'آخر دخول 17:30؛ الدخول مجاني الثلاثاء',source:'https://sakipsabancimuzesi.org/en/visit'},
'Istanbul Archaeological Museums':{closed:[],hours:'09:00–18:30',note:'شباك التذاكر حتى 17:30؛ بعض القاعات مغلقة مؤقتًا',source:'https://muze.gov.tr/muze-detay?DistId=IAR&SectionId=IAR01'},
'Galata Tower':{closed:[],hours:'08:30–18:30',note:'شباك التذاكر حتى 18:14',source:'https://muze.gov.tr/muze-detay?distid=mrk&sectionid=glt04'},
'Turkish & Islamic Arts Museum':{closed:[],hours:'09:00–18:30',note:'شباك التذاكر حتى 17:30',source:'https://www.muze.gov.tr/muze-detay?DistId=TIE&SectionId=TIE01'},
'Istanbul Aquarium':{closed:[],hours:'10:00–19:00',byDay:{0:'10:00–20:00',6:'10:00–20:00'},source:'https://www.istanbulakvaryum.com/plan-your-visit/visiting-hours'}
});
Object.assign(rules,globalThis.VenueGuide?.hours||{});
const weekday=d=>new Date(d+'T12:00:00Z').getUTCDay();
const opening=p=>p.openingHours&&typeof p.openingHours==='object'&&Array.isArray(p.openingHours.closed)?p.openingHours:rules[p.name];
const closed=(p,d)=>!!opening(p)?.closed?.includes(weekday(d));
const coord=p=>PlannerCore.coordinates(p);
const query=p=>p?.preferAddress?[p.name,p.address].filter(Boolean).join(', '):coord(p)?`${p.lat},${p.lon}`:[p?.name,p?.address||trip()?.destination].filter(Boolean).join(', ');
function transitUrl(p,origin){const u=new URL('https://www.google.com/maps/dir/');u.searchParams.set('api','1');u.searchParams.set('destination',query(p));u.searchParams.set('travelmode','transit');if(origin)u.searchParams.set('origin',query(origin));return u.href;}
function main(x,d){return x.places.filter(p=>p.date===d&&p.listId!=='extra').sort((a,b)=>(a.order||0)-(b.order||0));}
function predecessor(x,p){const list=main(x,p.date),i=list.findIndex(v=>v.id===p.id);return i>0?list[i-1]:x.hotel;}
function hoursText(r,d){return r?.byDay?.[weekday(d)]||r?.byMonth?.[Number(String(d||'').slice(5,7))]||r?.hours||'';}
function hoursPanel(p){const r=opening(p),x=trip();if(!x)return '';const publicPlace=r?.kind==='public',conditional=r?.kind==='conditional',secondary=r?.confidence==='secondary';return `<details class="opening-panel" ${closed(p,p.date)?'open':''}><summary>${L('الدوام وأيام الفتح','Hours and opening days')} ${closed(p,p.date)?'<b class="closure-alert">'+L('مغلق في يوم الزيارة','Closed on planned day')+'</b>':''}</summary><div class="opening-days">${days(x).map(d=>{const s=closed(p,d)?'closed':publicPlace?'public':!r||conditional?'unknown':secondary?'secondary':'open';return `<span class="opening-day ${s} ${p.date===d?'planned':''}" title="${esc(d)}"><b>${shortDay(d)}</b><small>${new Intl.DateTimeFormat(lang==='ar'?'ar-JO':'en-GB',{weekday:'short',timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'))}</small><small>${s==='closed'?L('مغلق','Closed'):s==='public'?L('مكان عام','Public area'):r?esc(hoursText(r,d)||L('تحتاج تأكيدًا','Confirm hours')):L('غير موثّق','Unverified')}</small></span>`;}).join('')}</div>${r?`<small>${r.note?esc(lang==='ar'?r.note:r.noteEn||'See source for entry conditions')+' · ':''}${publicPlace?'':L('جدول منشور؛ الإغلاق الطارئ ممكن','Published schedule; exceptional closures possible')}${r.source?` · <a href="${esc(r.source)}" target="_blank" rel="noopener">${secondary?L('دليل خارجي · أكد قبل الزيارة','Directory · confirm before visiting'):L('المصدر الرسمي','Official source')}</a> · ${L('راجعناه 5 أكتوبر 2026','Reviewed 5 Oct 2026')}`:''}</small>`:`<small>${p.category==='mosque'?L('زيارة المساجد تتأثر بالصلاة؛ المواعيد السياحية تحتاج تأكيدًا.','Mosque visits depend on prayers; tourist hours need confirmation.'):L('لم نجد دوامًا موثوقًا لهذا المكان/الفرع؛ لا يوجد ضمان أنه مفتوح.','No reliable hours for this venue/branch; opening is not guaranteed.')} <a href="${esc(mapUrl(p))}" target="_blank" rel="noopener">${L('تحقّق من الفرع والدوام','Verify branch and hours')}</a></small>`}</details>`;}
function accessPanel(p){const from=predecessor(trip(),p);return `<section class="transit-access"><strong>🚋 ${L('الوصول بالمواصلات العامة','Get here by public transport')}</strong><p class="transit-origin">${L('من موقعك الحالي: مترو، ترام، باص أو عبّارة حسب المتاح، مع المشي والتبديلات.','From your current location: metro, tram, bus or ferry, including walks and transfers.')}</p><div class="action-bar"><a class="tiny primary" href="${esc(transitUrl(p))}" target="_blank" rel="noopener">${L('المواصلات من موقعي الآن ↗','Transit from my location ↗')}</a><button class="tiny" data-action="liveTransit" data-id="${esc(p.id)}">${L('حدّد موقعي واحسب الطريق','Locate me and calculate route')}</button>${from?`<a class="tiny" href="${esc(transitUrl(p,from))}" target="_blank" rel="noopener">${L('من ','From ')}${esc(from.name)} ↗</a>`:''}</div><div class="live-transit-result" data-transit-id="${esc(p.id)}" aria-live="polite"></div></section>`;}
placeCard=function(p,ordered){return oldCard(p,ordered).replace('<div class="place-actions">',hoursPanel(p)+accessPanel(p)+'<div class="place-actions">');};
travelMode='transit';navigationUrl=p=>transitUrl(p);
// Google transit does not support waypoints. Each pair must be routed separately.
googleDirections=stops=>stops.length>1?transitUrl(stops[1],stops[0]):'';
routeGroups=stops=>{const all=trip()?.hotel?[trip().hotel,...stops]:stops.slice();return all.slice(1).map((p,i)=>[all[i],p]);};
function key(){return localStorage.getItem('rahlati-google-key')||'';}
function loadGoogle(){if(globalThis.google?.maps?.Map)return Promise.resolve();if(loader)return loader;if(!key())return Promise.reject(Error('NO_KEY'));loader=new Promise((resolve,reject)=>{const script=document.createElement('script');const timer=setTimeout(()=>reject(Error('MAP_TIMEOUT')),20000);globalThis.rahlatiMapReady=()=>{clearTimeout(timer);resolve();};globalThis.gm_authFailure=()=>{clearTimeout(timer);reject(Error('AUTH_FAILURE'));};script.src='https://maps.googleapis.com/maps/api/js?key='+encodeURIComponent(key())+'&callback=rahlatiMapReady&loading=async&v=weekly';script.onerror=()=>{clearTimeout(timer);reject(Error('MAP_LOAD'));};document.head.appendChild(script);});loader.catch(()=>loader=null);return loader;}
const routeCache=new Map();
async function route(origin,destination,departure){if(!key())throw Error('NO_KEY');if(!coord(destination)&&!destination.address?.trim())throw Error('AMBIGUOUS_PLACE');await loadGoogle();const point=p=>p.preferAddress?query(p):coord(p)?{lat:Number(p.lat),lng:Number(p.lon)}:query(p);const cacheId=JSON.stringify([query(origin),query(destination),Math.floor(departure.getTime()/300000),lang,localStorage.getItem('rahlati-transit-preference')||'FEWER_TRANSFERS']);if(routeCache.has(cacheId))return routeCache.get(cacheId);const request=(async()=>{const {Route}=await google.maps.importLibrary('routes');const data=await Route.computeRoutes({origin:point(origin),destination:point(destination),travelMode:'TRANSIT',departureTime:departure,transitPreference:{routingPreference:localStorage.getItem('rahlati-transit-preference')||'FEWER_TRANSFERS'},language:lang==='ar'?'ar':'en',fields:['path','legs','durationMillis','distanceMeters']});if(!data.routes?.length)throw Error('NO_ROUTE');return data.routes[0];})();routeCache.set(cacheId,request);try{return await request;}catch(e){routeCache.delete(cacheId);throw e;}}
const seconds=r=>Number(r.durationMillis||0)/1000;
const asPoint=p=>p?.latLng?asPoint(p.latLng):p&&typeof p.lat==='function'?{lat:p.lat(),lng:p.lng()}:p&&Number.isFinite(Number(p.lat))?{lat:Number(p.lat),lng:Number(p.lng)}:null;
function decode(s){let i=0,lat=0,lng=0,path=[];while(i<s.length){let values=[];for(let k=0;k<2;k++){let result=0,shift=0,b;do{b=s.charCodeAt(i++)-63;result|=(b&31)<<shift;shift+=5;}while(b>=32&&i<s.length);values.push(result&1?~(result>>1):result>>1);}lat+=values[0];lng+=values[1];path.push({lat:lat/1e5,lng:lng/1e5});}return path;}
function stepsHtml(r){const clock=d=>d?new Intl.DateTimeFormat(lang==='ar'?'ar-JO':'en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'}).format(new Date(d)):'';return `<p><b>${Math.ceil(seconds(r)/60)} ${L('دقيقة','min')}</b> · ${(Number(r.distanceMeters||0)/1000).toFixed(1)} ${L('كم','km')}</p><ol class="transit-steps">${(r.legs||[]).flatMap(l=>l.steps||[]).map(s=>{const d=s.transitDetails;if(!d)return `<li>🚶 ${esc(s.instructions||L('مشي','Walk'))}</li>`;const line=d.transitLine||{};return `<li><b>${esc(line.shortName||line.name||L('مواصلات','Transit'))}</b> · ${esc(line.vehicle?.name||'')}<br>${esc(d.departureStop?.name||'')} ${clock(d.departureTime)} → ${esc(d.arrivalStop?.name||'')} ${clock(d.arrivalTime)}${d.headsign?'<br>'+L('باتجاه ','Towards ')+esc(d.headsign):''}${d.stopCount?' · '+d.stopCount+' '+L('محطات','stops'):''}</li>`;}).join('')}</ol><small>${L('الأوقات بتوقيت إسطنبول؛ راجع الرحلة قبل الانطلاق.','Times in Istanbul; recheck before departure.')}</small>`;}
function mapPanel(x){if(mapFilter==='all'&&!globalThis.RahlatiShowAllDays)mapFilter=days(x)[day];const ds=days(x),selected=mapFilter==='all'?ds:[mapFilter];return `<div class="section-title"><h2>${L('مسارات المواصلات العامة','Public transport routes')}</h2><button class="btn" data-action="configureTransit">${L('إعداد الخريطة','Map setup')}</button></div><label class="field">${t('day')}<select id="mapFilter"><option value="all" ${mapFilter==='all'?'selected':''}>${t('categoryAll')}</option>${ds.map((d,i)=>`<option value="${d}" ${mapFilter===d?'selected':''}>${t('day')} ${i+1} · ${fmt(d)}</option>`).join('')}</select></label><div class="route-legend">${selected.map(d=>`<span style="--route-color:${colorForDay(x,d)}">${t('day')} ${ds.indexOf(d)+1} · ${shortDay(d)}</span>`).join('')}</div><div class="action-bar"><button class="btn primary" data-action="calculateTransitMap">${L('احسب وارسم مسار اختياراتي','Calculate and draw my selected route')}</button><label class="check-label"><input id="transitShowExtras" type="checkbox"> ${L('أظهر الإضافيات الموثقة على الخريطة','Show located extras on map')}</label></div><small>${L('الحساب يبدأ عند الضغط؛ كل محطة تُحسب من سابقتها بالمواصلات. الإضافيات خارج المسار حتى تختارها.','Calculation starts on demand; each leg uses public transport. Extras stay outside the route until selected.')}</small><div id="transitMap" class="transit-map"><p>${key()?L('جاري تحميل الخريطة…','Loading map…'):L('عرض المسارات الملوّنة داخل التطبيق يحتاج تفعيل Google Maps. الروابط أدناه تعمل الآن بدون تفعيل.','In-app colored routes require Google Maps activation. The links below work now without activation.')}</p></div><p id="transitMapStatus" class="muted" aria-live="polite"></p>${selected.map(d=>{const list=main(x,d);return `<section class="panel" style="border-inline-start:5px solid ${colorForDay(x,d)}"><h3>${t('day')} ${ds.indexOf(d)+1} · ${fmt(d)}</h3>${list.map((p,i)=>`<div class="route-stop"><span class="google-number" style="background:${colorForDay(x,d)}">${p.sequence||i+1}</span><div><strong>${esc(p.name)}</strong>${closed(p,d)?`<b class="closure-alert">${L('مغلق في هذا اليوم','Closed this day')}</b>`:''}<div><a href="${esc(transitUrl(p,i?list[i-1]:x.hotel))}" target="_blank" rel="noopener">${L('المواصلات من ','Transit from ')}${esc(i?list[i-1].name:x.hotel?.name||L('موقعك','your location'))} ↗</a></div><div data-route-step="${esc(p.id)}"></div></div></div>`).join('')||L('لا توجد محطات أساسية.','No main stops.')}${x.places.some(p=>p.date===d&&p.listId==='extra')?`<details><summary>${L('أماكن إضافية، خارج مسار اليوم','Extra places, outside the day route')}</summary>${x.places.filter(p=>p.date===d&&p.listId==='extra').map(p=>`<p><a href="${esc(transitUrl(p))}" target="_blank" rel="noopener">${esc(p.name)} ↗</a></p>`).join('')}</details>`:''}</section>`;}).join('')}`;}
renderTab=function(x){let html=tab==='mapView'?mapPanel(x):oldTab(x);if(tab==='itinerary'){html=html.replace(/<button[^>]*data-action="mode"[^>]*data-mode="(?:walking|driving)"[^>]*>[\s\S]*?<\/button>/g,'');const d=days(x)[day],bad=main(x,d).filter(p=>closed(p,d));if(bad.length)html=`<div class="closure-banner">${L('تنبيه: أماكن مغلقة في هذا اليوم: ','Closed on this day: ')}${bad.map(p=>esc(p.name)).join('، ')}. ${L('استخدم «نقل ليوم» لاختيار يوم مفتوح.','Use Move to day to pick an open day.')}</div>`+html;}return html;};
async function drawMap(token){const node=document.getElementById('transitMap');if(!node||!key())return;let status=document.getElementById('transitMapStatus');try{await loadGoogle();if(token!==generation||!node.isConnected)return;const x=trip(),selected=mapFilter==='all'?days(x):[mapFilter],map=new google.maps.Map(node,{center:{lat:41.02,lng:28.98},zoom:12,mapTypeId:'roadmap',fullscreenControl:true}),bounds=new google.maps.LatLngBounds();const marker=(p,label,color)=>{if(!coord(p))return;const pos={lat:Number(p.lat),lng:Number(p.lon)};bounds.extend(pos);const m=new google.maps.Marker({map,position:pos,title:p.name,label:{text:String(label),color:'#fff'},icon:{path:google.maps.SymbolPath.CIRCLE,scale:16,fillColor:color,fillOpacity:1,strokeColor:'#fff',strokeWeight:2}});m.addListener('click',()=>{if(p.id)details(p);});};if(x.hotel)marker(x.hotel,'H','#163a43');let failures=0;for(const d of selected){const list=main(x,d);list.forEach((p,i)=>marker(p,p.sequence||i+1,colorForDay(x,d)));}if(document.getElementById('transitShowExtras')?.checked){for(const p of x.places.filter(p=>selected.includes(p.date)&&p.listId==='extra'))marker(p,'+'+(p.sequence||''),colorForDay(x,p.date));}if(!bounds.isEmpty())map.fitBounds(bounds);for(const d of selected){let from=x.hotel,departure=new Date(d+'T'+(x.dayStart?.[d]||'09:00')+':00+03:00');if(departure<Date.now())departure=new Date();for(const p of main(x,d)){if(token!==generation||!node.isConnected)return;if(from){try{const r=await route(from,p,departure);if(token!==generation)return;const endpoint=asPoint(r.legs?.at(-1)?.endLocation)||asPoint(r.path?.at(-1));if(!coord(p)&&endpoint)marker({...p,lat:endpoint.lat,lon:endpoint.lng},p.sequence||main(x,d).indexOf(p)+1,colorForDay(x,d));new google.maps.Polyline({map,path:r.path||[],strokeColor:colorForDay(x,d),strokeWeight:5,strokeOpacity:.85});const output=[...document.querySelectorAll('[data-route-step]')].find(n=>n.dataset.routeStep===p.id);if(output)output.innerHTML=stepsHtml(r);const arrival=departure.getTime()+seconds(r)*1000;const planned=p.time?new Date(d+'T'+p.time+':00+03:00').getTime():0;departure=new Date(Math.max(arrival,planned)+Math.max(15,Number(p.duration)||globalThis.VenueGuide?.profiles[p.name]?.minutes||60)*60000+15*60000);}catch{failures++;}}from=p;}}if(!bounds.isEmpty())map.fitBounds(bounds);status.textContent=failures?L(`${failures} انتقالات تعذّر حسابها؛ افتح روابط Google Maps.`,`${failures} legs unavailable; open Google Maps links.`):L('المسارات الفعلية بالمواصلات، والأرقام حسب ترتيب اليوم.','Actual transit routes; numbers follow each day’s order.');}catch{if(node.isConnected)node.textContent=L('تعذّر تشغيل Google Maps. استخدم روابط المواصلات أدناه وتحقق من إعداد الخريطة.','Google Maps could not load. Use transit links below and check map setup.');}}
render=function(){generation++;oldRender();const token=generation;};
const priorClose=close;close=function(){if(locationWatch!==null){navigator.geolocation?.clearWatch(locationWatch);locationWatch=null;}priorClose();};
function configure(){modal(L('إعداد Google Maps','Google Maps setup'),`<form><p>${L('المسارات تحتاج مفتاحك في Google Maps. المفتاح التجريبي مجاني بحد يومي وبدون فوترة، لكنه للمعاينة فقط. للاعتماد خلال السفر استخدم مفتاح إنتاج مع تفعيل Maps JavaScript API وRoutes API.','Routes need your Google Maps key. A demo key has a free daily quota without billing, for previews only. For travel use, enable Maps JavaScript API and Routes API on a production key.')}</p><p><a href="https://developers.google.com/maps/documentation/javascript/demo-key" target="_blank" rel="noopener">${L('المفتاح التجريبي: دليل Google الرسمي ↗','Demo key: official Google guide ↗')}</a></p><p>${L('قيد المفتاح بموقع mothana992.github.io وبالخدمات المطلوبة. الإنتاج قد يترتب عليه تكلفة؛ اضبط الحصة اليومية في حسابك.','Restrict the key to mothana992.github.io and required APIs. Production may incur charges; set daily quotas in your account.')}</p><label class="field">Google Maps API key<input name="mapKey" type="password" autocomplete="off" value="${esc(key())}"></label><label class="field">${L('تفضيل المواصلات للعائلة','Family transit preference')}<select name="preference"><option value="FEWER_TRANSFERS">${L('تبديلات أقل','Fewer transfers')}</option><option value="LESS_WALKING" ${localStorage.getItem('rahlati-transit-preference')==='LESS_WALKING'?'selected':''}>${L('مشي أقل','Less walking')}</option></select></label><small>${L('محفوظ على جهازك فقط؛ لا يُرفع للمشروع. تحديث المفتاح يتطلب إعادة تحميل الصفحة بعد الحفظ.','Saved on your device only; not published. Reload after changing the key.')}</small>${formButtons()}</form>`,d=>{localStorage.setItem('rahlati-google-key',d.mapKey.trim());localStorage.setItem('rahlati-transit-preference',d.preference);routeCache.clear();loader=null;});}
settings=function(){oldSettings();document.getElementById('modalBody').insertAdjacentHTML('beforeend',`<section class="panel"><h3>${L('المواصلات والخريطة','Transit and map')}</h3><button class="btn" data-action="configureTransit">${L('إعداد Google Maps','Set up Google Maps')}</button></section>`);};
async function live(p){modal(L('المواصلات من موقعك الحالي','Transit from your location'),`<h3>${esc(p.name)}</h3><div id="liveRoute" aria-live="polite">${L('جاري تحديد الموقع…','Locating you…')}</div><a class="btn primary" href="${esc(transitUrl(p))}" target="_blank" rel="noopener">${L('افتح المواصلات في Google Maps ↗','Open transit in Google Maps ↗')}</a>`,null);const output=document.getElementById('liveRoute');if(!navigator.geolocation){output.textContent=L('تحديد الموقع غير متاح؛ استخدم Google Maps.','Location unavailable; use Google Maps.');return;}if(locationWatch!==null)navigator.geolocation.clearWatch(locationWatch);let busy=false,lastRun=0;locationWatch=navigator.geolocation.watchPosition(async pos=>{lastPosition={lat:pos.coords.latitude,lon:pos.coords.longitude};if(!output.isConnected){navigator.geolocation.clearWatch(locationWatch);locationWatch=null;return;}if(busy||Date.now()-lastRun<60000)return;busy=true;lastRun=Date.now();const link=output.parentElement.querySelector('a');if(link)link.href=transitUrl(p,lastPosition);if(!key()){output.textContent=L('تم تحديد موقعك. الرابط يعرض المحطات والتبديلات وأوقات الانطلاق بالمواصلات حسب موقعك الحالي. عرض التفاصيل هنا يحتاج تفعيل الخريطة.','Location found. The link shows current transit stops, transfers and departures. In-app details require map activation.');busy=false;return;}try{const r=await route(lastPosition,p,new Date());if(output.isConnected)output.innerHTML=stepsHtml(r)+`<small>${L('يتحدّث عند تغيّر موقعك، بفاصل دقيقة بين الحسابات.','Updates as your location changes, at most once per minute.')}</small>`;}catch{if(output.isConnected)output.textContent=L('تعذّر حساب المسار هنا؛ افتح Google Maps.','Route unavailable here; open Google Maps.');}finally{busy=false;}},()=>{if(output.isConnected)output.textContent=L('تعذّر تحديد الموقع. اسمح بصلاحية الموقع أو افتح Google Maps وحدّد نقطة الانطلاق.','Could not locate you. Allow location access or set the origin in Google Maps.');},{enableHighAccuracy:true,timeout:15000,maximumAge:15000});}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;if(b.dataset.action==='calculateTransitMap')drawMap(generation);if(b.dataset.action==='configureTransit')configure();if(b.dataset.action==='liveTransit'){const p=trip()?.places.find(p=>p.id===b.dataset.id);if(p)live(p);}});
globalThis.RahlatiTransit={transitUrl,closed,decode,predecessor,rules,opening,hoursText,route,stepsHtml};
document.addEventListener('change',e=>{if(e.target.id==='mapFilter')globalThis.RahlatiShowAllDays=e.target.value==='all';},true);
render();
})();
