/* Complete, recoverable source snapshot. Source notes and local edits are separate. */
(function(){
'use strict';
const S=WanderlogSnapshot,T=RahlatiTransit,L=(a,b)=>lang==='ar'?a:b;
const dates=Object.keys(IstanbulPlan.days);
const plan={
'2026-10-10':[['Grand Bazaar','16:00',60]],
'2026-10-11':[['Kariye Mosque','10:45',60],['Suleymaniye Mosque','12:30',40],['Rustem Pasha Mosque','13:45',30],['Hagia Sophia Grand Mosque','15:00',60],['The Blue Mosque','16:15',40],['Arasta Çarşısı','17:10',40]],
'2026-10-12':[['Topkapi Palace Museum','10:30',180],['Turkish & Islamic Arts Museum','15:00',75],['Gülhane Park','17:00',45]],
'2026-10-13':[['Galata Tower','10:45',60],['Galataport','12:15',60],['Karaköy','14:15',60],['Beyoğlu','17:00',75]],
'2026-10-14':[['Beylerbeyi Palace','11:15',75],["Maiden's Tower",'14:00',75],['Kadıköy','17:00',90]],
'2026-10-15':[['Dolmabahçe Palace','10:45',150],['Yıldız Park','14:30',60],['Ortaköy','16:00',75]],
'2026-10-16':[['Rahmi M. Koç Museum','10:30',120],['Teleferik Pierreloti','14:00',90]],
'2026-10-17':[['Istanbul Aquarium','11:00',120],['Aqua Florya','17:00',90]],
'2026-10-18':[['Forum Istanbul','10:30',90]]};
const headings=['الوصول والبازار على راحتكم','كارييه والفاتح ثم السلطان أحمد','توبكابي وتفعيل كرت المتاحف','غلاطة وكاراكوي وبيوغلو','الجانب الآسيوي والقصر وبرج الفتاة','دولمة بهجة ويلدز وأورتاكوي','رحمي كوتش وتلفريك بيير لوتي','فلوريا والأكواريوم وغروب البحر','يوم العودة — قريب من الفندق'];
const intros=[
'وصول IST الساعة 12:45؛ بعد الجوازات والحقائب والمواصلات وتسجيل الفندق. البازار 16:00 اختياري إذا تأخر الوصول؛ انقله ليوم الاثنين إذا فاتك، وليس الأحد لأنه مغلق. بقية المساء راحة وأكل قريب.',
'كارييه أولًا لأنه مغلق للسياح الجمعة. استراحة وغداء بعد رستم باشا. زيارة المسجد الأزرق قبل آخر دخول 16:30. الصهريج بديل مشروط بتأكيد الفتح؛ لا تضفه فوق الست محطات.',
'الكرت يبدأ عند أول دخول توبكابي، وخطة استخدامه 12–16 أكتوبر. الآثار محفوظ كبديل لأنك كاتب مش ضروري؛ ممكن بدل غولهانة بعد اختصار القصر. غداء 13:30–14:30.',
'أزلنا المتاحف التي شلتها من Wanderlog. غلاطة ضمن الكرت، وبقية اليوم مشي وتسوق وأكل. Sarmarine وساكاريا ضمن الخيارات ذات الأولوية من نوتسك. متحف مولوي بديل قريب إذا بدك تستغل الكرت أكثر.',
'بيلربي: اختَر القصر أو الحديقة فقط. قارب برج الفتاة منفصل ويتأثر بالطقس. غداء قبل القارب؛ بعده كاديكوي. الألعاب بديل لأنك كاتب مش ضروري. غازي بورما المحفوظ هو فرع بنديك؛ أبعد من كاديكوي فلا تجمعه تلقائيًا معها.',
'دولمة بهجة خارج الكرت ومغلق الاثنين. غداء واستراحة 13:15–14:15. إطلالة أورتاكوي مساء؛ مطاعم المنطقة تحت اليوم. رحلة العبارة من أمينونو تعتمد الجدول والرصيف الفعلي.',
'غداء بعد رحمي كوتش، ثم تلفريك TF2 ووقت للإطلالة. إميرغان وساريير وروملي مسار بديل للشمال إذا فضّلتهم بدل يوم القرن الذهبي؛ لا تجمع المسارين فوق بعض.',
'غداء واستراحة بجانب البحر ثم أكوا فلوريا عند الغروب حسب نوتسك. متحف الشوكولاتة في أسنيورت بديل نصف يوم مع وقت انتقال طويل، وفيالاند بديل مستقل؛ اختَر بدل الأكواريوم.',
'زيارة اختيارية قصيرة قرب الفندق. ارجع للحقائب قبل 16:00 وانطلق للمطار نحو 16:30، مع هدف الوصول IST قبل 18:30 لرحلة 21:30. افحص وقت المواصلات الفعلي وأبكر إذا احتاج الطريق؛ الوصول عمّان 00:01 يوم 19 أكتوبر.'
];
const flights=[{id:'flight-rj165',type:'flight',name:'RJ165 — عمّان → إسطنبول',provider:'Royal Jordanian',start:'2026-10-10',end:'2026-10-10',departTime:'10:05',arrivalTime:'12:45',from:'AMM',to:'IST',note:'ذهاب مؤكد من صورة التذكرة: المغادرة 10:05 والوصول 12:45 بالتوقيت المحلي؛ مباشر.'},{id:'flight-rj164',type:'flight',name:'RJ164 — إسطنبول → عمّان',provider:'Royal Jordanian',start:'2026-10-18',end:'2026-10-19',departTime:'21:30',arrivalTime:'00:01',from:'IST',to:'AMM',note:'عودة مؤكدة من صورة التذكرة: المغادرة 18 أكتوبر 21:30، الوصول 19 أكتوبر 00:01 بالتوقيت المحلي؛ مباشر.'}];
function eligible(x){return x.start==='2026-10-10'&&x.end==='2026-10-18'&&x.places?.some(p=>p.name==='Topkapi Palace Museum')&&x.places.length>=100;}
function category(r){const s=r.categories.join(' ').toLowerCase();if(/restaurant|shop|bakery|cafeteria|store/.test(s)&&!/shopping|museum/.test(s))return /cafe|coffee|dessert|pastry|ice cream/.test(s)?'cafe':'food';if(/cafe|coffee/.test(s))return 'cafe';if(/museum|aquarium/.test(s))return'museum';if(/mosque/.test(s))return'mosque';if(/mall|bazar/.test(s))return'shopping';if(/park|garden/.test(s))return'park';return'attraction';}
function apply(x){if(!eligible(x)||x.sourceSyncVersion>=S.version)return false;
 x.sourceSyncUndo={places:structuredCopy(x.places),dayPlans:structuredCopy(x.dayPlans),dayStart:structuredCopy(x.dayStart),bookings:structuredCopy(x.bookings||[])};
 const old=x.places,used=new Set(),next=[];let added=0;
 for(const r of S.places){let p=old.find(p=>!used.has(p.id)&&p.name===r.name);if(p)used.add(p.id);else{added++;p={id:'wanderlog-'+r.sourceId.split('_').at(-1),name:r.name,date:r.name==='Pelit Chocolate Museum'?'2026-10-17':r.name==='Teleferik Pierreloti'?'2026-10-16':'2026-10-16',listId:'extra',time:'',duration:r.name==='Pelit Chocolate Museum'?90:60,order:100+next.length,visited:false,comments:[]};}
 p.wanderlogId=r.sourceId;p.sourceIds=r.sourceIds||[r.sourceId];p.sourceNumbers=r.sourceNumbers;p.sourceNote=r.sourceNote;p.sourceCategories=r.categories;p.sourceUrl=S.url+'#'+r.sourceId;p.sourceHours=r.sourceHours;p.sourceStatus=r.sourceStatus||'';
 if(r.address){if(p.address!==r.address){delete p.lat;delete p.lon;}p.address=r.address;p.preferAddress=true;p.addressSource=p.sourceUrl;p.locationNote='';}
 for(const k of ['rating','ratingCount','phone','website','googleMapsUrl','typicalDuration'])if(r[k]!==undefined)p[k]=r[k];
 const official=T.rules[p.name];if(r.sourceHours&&(!official||official.confidence==='secondary'||official.kind==='conditional'))p.openingHours=r.sourceHours;
 if(p.name==='Hagia Sophia Grand Mosque')p.openingHours={closed:[],kind:'conditional',confidence:'secondary',source:p.sourceUrl,note:'عرض المصدر 24 ساعة يخص المسجد ولا يثبت ساعات زيارة معرض السياح؛ تأكد من شباك السياح قبل الزيارة.'};
 if(p.name==='Gümüşyolu Çk Sk')p.category='park';else if(!p.category)p.category=category(r);
 if(p.name==='Gümüşyolu Çk Sk')p.date='2026-10-14';
 if(p.name==='Beltur')p.date='2026-10-14';if(p.name==='Lokma'||p.name==='Beyazpark Kafe'||p.name==='İskele İzmir Lokmacısı')p.date='2026-10-16';if(p.name==='Rauf Un Yeri')p.locationNote='المكان المحفوظ في سابنجا، خارج إسطنبول؛ رحلة مستقلة وليست إضافة قصيرة لهذا اليوم.';
 if(p.name==='Gaziburma Mustafa')p.locationNote='فرعك المحفوظ بنديك، وليس كوزياتاغي؛ انتقال إضافي طويل من كاديكوي. مغلق الأحد حسب المصدر.';
 if(p.name==='Basilica Cistern')p.sourceStatus='تنبيه إغلاق مؤقت في Wanderlog؛ لم نثبت الفتح الحالي من الموقع الرسمي. يبقى بديلًا حتى التأكيد.';
 next.push(p);}
 const baseline=new Set(WanderlogSnapshot.previousNames||[]);const removed=old.filter(p=>!used.has(p.id)&&(p.wanderlogId||baseline.has(p.name)));next.push(...old.filter(p=>!used.has(p.id)&&!removed.includes(p)));x.sourceRemovedArchive=[...(x.sourceRemovedArchive||[]),...removed];x.places=next;
 for(const p of next){p.listId='extra';p.time='';}
 for(const [d,items]of Object.entries(plan))items.forEach(([n,time,duration],order)=>{const p=next.find(p=>p.name===n);if(p)Object.assign(p,{date:d,time,duration,order,listId:''});});
 const arch=next.find(p=>p.name==='Istanbul Archaeological Museums');if(arch)arch.date='2026-10-12';const gul=next.find(p=>p.name==='Gülhane Park');if(gul)gul.date='2026-10-12';
 x.dayPlans=Object.fromEntries(dates.map((d,i)=>[d,{areaAr:headings[i],areaEn:headings[i],introAr:intros[i],introEn:intros[i]}]));x.dayStart=Object.fromEntries(dates.map(d=>[d,d==='2026-10-10'?'16:00':'10:00']));
 x.bookings??=[];for(const f of flights)if(!x.bookings.some(b=>b.id===f.id||b.name?.includes(f.id==='flight-rj165'?'RJ165':'RJ164')))x.bookings.push({...f});
 x.sourceSyncVersion=S.version;x.sourceSyncSummary={added,removed:removed.length,sourceCards:122,places:next.length,notes:next.filter(p=>p.sourceNote).length,checked:S.checked};x.planVersion=45;IstanbulPlan.number(x);return true;
}
function structuredCopy(v){return v===undefined?undefined:JSON.parse(JSON.stringify(v));}
function note(p){const text=p.userNote??p.sourceNote??'';return `<section class="personal-note"><strong>${L('✎ نوتسي','✎ My notes')}</strong><p>${esc(text||L('أضف نوتة للمكان','Add a note'))}</p><button class="tiny" data-action="editVenueNote" data-id="${esc(p.id)}">${L('تعديل النوتة','Edit note')}</button>${p.userNote!==undefined&&p.sourceNote?`<details><summary>${L('النوتة الأصلية من Wanderlog','Original Wanderlog note')}</summary><p>${esc(p.sourceNote)}</p></details>`:''}</section>`;}
function costs(p){const c=p.admissionOverride||VenueCosts[p.name],included=IstanbulPlan.passNames.includes(p.name),food=['food','cafe'].includes(p.category),free=['park','shopping','mosque'].includes(p.category)&&!c;let text=c?.amount!==undefined?`${c.amount} ${c.currency}`:food?L('حسب طلبك؛ ليست تذكرة متحف','Pay for your order'):free?L('دخول عام بدون تذكرة؛ الأنشطة والأكل منفصلة','Public entry; activities and food extra'):L('السعر الحالي غير مثبت','Current price unverified');return `<section class="venue-price"><b>🎟 ${L('الدخول','Admission')}: <span dir="auto">${esc(text)}</span></b><p>${included?L('مشمول بكرت Museum Pass Istanbul؛ الدخول الإضافي 0 خلال صلاحية الكرت، مرة واحدة.','Museum Pass Istanbul included; no extra admission during validity, once.'):food?L('خارج كرت المتاحف — مطعم/كافيه','Outside Museum Pass — food venue'):free?L('لا تحتاج الكرت للدخول العام','Pass not needed for public entry'):L('غير مشمول بكرت Museum Pass Istanbul','Not included in Museum Pass Istanbul')}</p>${c?.options?.map(o=>`<p>${esc(o.label)}: ${o.amount} ${o.currency}</p>`).join('')||''}${c?.extra?`<p>＋ ${esc(c.extra.label)}: ${c.extra.amount} ${c.extra.currency} ${L('منفصل حتى مع الكرت','extra even with pass')}</p>`:''}${c?.note?`<small>${esc(c.note)}</small>`:''}${c?.source?`<p><a href="${esc(c.source)}" target="_blank" rel="noopener">${L('مصدر الدخولية','Admission source')} ↗</a> · ${esc(c.checked||'')} · ${L('للبالغ الأجنبي؛ يتغير السعر','Foreign adult; price may change')}</p>`:''}<button class="tiny" data-action="editVenueCost" data-id="${esc(p.id)}">${L('حدّث السعر عندي','Update my price')}</button></section>`;}
function info(p){return `${p.sourceStatus?`<p class="visit-warning">${esc(p.sourceStatus)}</p>`:''}${p.rating?`<p>★ ${p.rating} (${p.ratingCount||0}) · ${L('تقييم من Wanderlog بتاريخ 6 أكتوبر','Wanderlog rating as of 6 October')}</p>`:''}${p.typicalDuration?`<p>${L('مدة الزيارة في المصدر: ','Typical source visit: ')}${esc(p.typicalDuration)} · ${L('وقت خطتك قد يكون أطول','Your planned time may be longer')}</p>`:''}<div class="action-bar">${[['phone','اتصال','Call'],['website','موقع المكان','Website'],['googleMapsUrl','فرعك على Google Maps','Your Google Maps pin']].filter(([k])=>p[k]).map(([k,a,b])=>`<a class="tiny" href="${esc(k==='phone'?'tel:'+p[k]:p[k])}" target="_blank" rel="noopener">${L(a,b)} ↗</a>`).join('')}</div>${T.hoursPanel(p)}${costs(p)}${note(p)}`;}
function flightPanel(x){const fs=(x.bookings||[]).filter(b=>b.id==='flight-rj165'||b.id==='flight-rj164');return fs.length?`<details class="panel flights"><summary>✈ ${L('الطيران المؤكد — الذهاب والعودة','Confirmed outbound and return flights')}</summary><p><a href="https://www.google.com/maps/dir/?api=1&amp;destination=Istanbul%20Airport&amp;travelmode=transit" target="_blank" rel="noopener">المواصلات العامة للمطار من موقعي ↗</a></p>${fs.map(f=>`<h4>${esc(f.name)}</h4><p dir="auto">${f.start} · ${f.departTime} ${f.from} → ${f.end} · ${f.arrivalTime} ${f.to}</p><p>${esc(f.provider)} · ${L('توقيت محلي · من صورة تذكرتك','Local times · from your ticket')}</p><button class="tiny" data-action="editBooking" data-id="${f.id}">${L('تعديل الحجز','Edit booking')}</button>`).join('')}</details>`:'';}
for(const p of S.places){if(!VenueGuide.profiles[p.name])VenueGuide.profiles[p.name]={minutes:p.name==='Pelit Chocolate Museum'?90:p.name==='Teleferik Pierreloti'?90:45,window:'10:00–17:00',homeDay:p.name==='Pelit Chocolate Museum'?'2026-10-17':'2026-10-16',advice:p.name==='Pelit Chocolate Museum'?'أسنيورت: نصف يوم بديل مع انتقال طويل بالمواصلات.':''};}
T.rules['Pelit Chocolate Museum']={closed:[],hours:'10:00–17:00',source:'https://www.pelitcikolatamuse.com/sss'};T.rules['Teleferik Pierreloti']={closed:[],hours:'08:00–22:00',source:'https://www.metro.istanbul/Hatlarimiz/HatDetay?hat=TF2',note:'الشتاء حتى 22:00 والصيف حتى 23:00؛ تتوقف الخدمة عند الرياح/الصيانة.'};
const prior=render;render=function(){let changed=false;for(const x of trips)changed=apply(x)||changed;for(const x of trips)if(x.sourceSyncVersion===49)for(const p of x.places){const rule=T.rules[p.name];if(rule&&rule.confidence!=='secondary'&&rule.kind!=='conditional'&&p.openingHours?.source?.includes('wanderlog.com')){delete p.openingHours;changed=true;}}if(changed)persist();prior();};
const oldDetails=details;details=function(p){oldDetails(p);if(p?.wanderlogId&&$('#modalBody'))$('#modalBody').insertAdjacentHTML('afterbegin',info(p));};
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]'),x=trip(),p=x?.places.find(p=>p.id===b?.dataset.id);if(!b)return;if(b.dataset.action==='editVenueNote'&&p)modal(L('نوتسي عند '+p.name,'My note: '+p.name),`<form><label class="field">${L('نوتة قابلة للتعديل','Editable note')}<textarea name="userNote" rows="6">${esc(p.userNote??p.sourceNote??'')}</textarea></label>${formButtons()}</form>`,d=>{p.userNote=d.userNote;});if(b.dataset.action==='editVenueCost'&&p){const c=p.admissionOverride||VenueCosts[p.name]||{};modal(L('الدخولية عندي','My admission price'),`<form><label class="field">${L('السعر للبالغ','Adult price')}<input name="amount" type="number" min="0" step="0.01" required value="${c.amount??''}"></label><label class="field">${L('العملة','Currency')}<select name="currency">${['TRY','EUR','JOD'].map(k=>`<option ${c.currency===k?'selected':''}>${k}</option>`).join('')}</select></label><label class="field">${L('ملاحظة','Note')}<textarea name="note">${esc(c.note||'')}</textarea></label>${formButtons()}</form>`,d=>{p.admissionOverride={amount:Number(d.amount),currency:d.currency,note:d.note,checked:new Date().toISOString().slice(0,10)};});}if(b.dataset.action==='restoreSourceRemoved'){modal(L('الأماكن التي شلتها من Wanderlog','Removed Wanderlog places'),`<p>${L('محفوظة للاسترجاع مع صورك وتعليقاتك؛ ليست ضمن برنامجك الحالي.','Recoverable with your photos and comments; outside the current plan.')}</p>${(x.sourceRemovedArchive||[]).map(p=>`<p>${esc(p.name)} <button class="tiny" data-action="restoreArchivedVenue" data-id="${esc(p.id)}">${L('استرجاع كبديل','Restore as alternative')}</button></p>`).join('')}`);}if(b.dataset.action==='restoreArchivedVenue'){const q=x.sourceRemovedArchive?.find(p=>p.id===b.dataset.id);if(q&&!x.places.some(p=>p.id===q.id)){x.places.push({...q,listId:'extra',time:''});x.sourceRemovedArchive=x.sourceRemovedArchive.filter(p=>p.id!==q.id);persist();close();render();}}});
globalThis.WanderlogSync={apply,note,costs,info,flightPanel,plan,flights};render();
})();
